# This needs to be run from repository's root


FROM node:18.16.1-alpine as compile

ARG NG_ENV

# create build dirs
RUN mkdir -p /app/build
WORKDIR /app/build

# copy sources and compile front
COPY frontend .
RUN npm install
RUN npx vite build --mode $NG_ENV


