# Use the official Node.js image as the base image
FROM node:14

ARG NG_ENV

# Set the working directory inside the container
WORKDIR /app

# Copy the package.json and package-lock.json files to the working directory
COPY backend/package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY backend/ .

# Expose the port on which the application will run
EXPOSE 5002

# Start the application
CMD [ "npm","run", "start" ]
