name: Deployment

on:
  push:
    branches:
      - main
      - deploy
  # allow user to start job manually
  workflow_dispatch:

jobs:
  # we define our job, which name is "build"
  build:
    # run job with OS: Linux Ubuntu
    runs-on: ubuntu-latest

    steps:
      # get the code from git repository
      - uses: actions/checkout@v3

      # use a specific Dockerfile (deploy/Dockerfile-nginx-front) to build a specific image with a web server (nginx) and compiled front files
      - name: Build FRONT image PROD
        run: docker build --build-arg NG_ENV=production -f ./deploy/Dockerfile-nginx-front -t ${{ secrets.DOCKERHUB_USERNAME }}/externatic-deploy-client:${GITHUB_REF##*/} .

      # build backend image with Spring Boot plugin for Maven
     
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # print generated images
      - name: Display local images
        run: docker images

      # deploy front image to Docker Hub (in DOCKERHUB_USERNAME namespace)
      - name: Push FRONT image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/externatic-deploy-client:${GITHUB_REF##*/}

      # deploy back image to Docker Hub (in DOCKERHUB_USERNAME namespace)
      - name: Push BACK image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/externatic-deploy-server:${GITHUB_REF##*/}
